<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\Cakki.API\" />
    <Folder Include="src\Cakki.Shared\" />
    <Folder Include="src\Cakki.Infrastructure\" />
    <Folder Include="src\Cakki.Application\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="src\cakki.api\Cakki.API.csproj" />
    <None Include="src\cakki.application\Cakki.Application.csproj" />
    <None Include="src\cakki.domain\Cakki.Domain.csproj" />
    <None Include="src\cakki.infrastructure\Cakki.Infrastructure.csproj" />
  </ItemGroup>

</Project>
